version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: my_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
      SCOUT_DRIVER: meilisearch
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: masterKey
    depends_on:
      - db
      - meilisearch
    command: >
      sh -c "
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: mysql:8.0
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:v1.2
    container_name: my_meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meili_data:/meili_data

volumes:
  dbdata:
  meili_data:
